global:
  scrape_interval: 5s  # Scrape every 5 seconds (adjust as needed)
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mac-metrics-api'
    static_configs:
      - targets: ['mac-metrics-api:8000']
